---

- name: install apache2
  ansible.builtin.apt:
    name: apache2

- name: apache - disable default sites
  ansible.builtin.command:
    cmd: a2dissite {{ item }}
    removes: "/etc/apache2/sites-enabled/{{ item }}.conf"
  with_items:
    - default-ssl
    - 000-default
  notify:
    - apache restart

- name: enable required apache modules
  # apache2_module fails due to some stupid output check and not cosidering the rc code
  # community.general.apache2_module:
  #   name: "{{ item }}"
  #   ignore_configcheck: true
  ansible.builtin.command: a2enmod {{ item }}
  args:
    creates: /etc/apache2/mods-enabled/{{ item }}.load
  notify: apache restart
  with_items: "{{ apache.a2enmod }}"

- name: disable apache modules
  community.general.apache2_module:
    name: "{{ item }}"
    state: absent
  notify: apache restart
  with_items: "{{ apache.a2dismod }}"

- name: copy apache SSLCertificate files
  ansible.builtin.copy:
    src: "{{ apache[item] | basename }}"
    dest: "{{ apache[item] }}"
    mode: "{{ (item == 'SSLCertificateFile') | bool | ternary('0600', '0644') }}"
  notify: apache restart
  with_items:
    - SSLCertificateFile
    - SSLCertificateKeyFile
  when:
    - apache.SSLCertificateCopy
    - apache.SSLCertificateFile is defined
    - apache.SSLCertificateFile | length > 0
    - apache.SSLCertificateKeyFile is defined
    - apache.SSLCertificateKeyFile | length > 0

- name: copy apache vhost config
  ansible.builtin.template:
    src: apache-xwiki.conf.j2
    dest: /etc/apache2/sites-available/xwiki.conf
    mode: '0644'
  notify: apache restart

- name: enable apache vhost
  ansible.builtin.command:
    cmd: a2ensite xwiki
    creates: /etc/apache2/sites-enabled/xwiki.conf
  notify: apache restart
