---

- name: install required and additional packages
  ansible.builtin.apt:
    name: "{{ xwiki_required_packages + xwiki_additional_packages }}"
    update_cache: true
  when: xwiki_required_packages

- name: xwiki apt key
  ansible.builtin.get_url:
    url: "{{ xwiki_repo_key_url }}"
    dest: "{{ xwiki_repo_key_dest }}"
    mode: "0644"

- name: xwiki apt repo
  ansible.builtin.apt_repository:
    repo: "{{ xwiki_repo }}"
    filename: xwiki

- name: dbconfig for xwiki
  ansible.builtin.template:
    src: dbconfig-xwiki.conf.j2
    dest: /etc/dbconfig-common/xwiki.conf
    backup: true
    mode: '0600'
  diff: false

- name: install xwiki ...
  ansible.builtin.apt:
    name: "{{ xwiki_packages }}"
    update_cache: true

- name: set xwiki package on hold
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items: "{{ xwiki_packages }}"
  when:
    - xwiki_hold_package | bool

- name: apply tomcat mem settings
  ansible.builtin.lineinfile:
    path: /etc/default/{{ xwiki_appserver }}
    line: 'JAVA_OPTS="${JAVA_OPTS} {{ tomcatjavaopts }}"'
    insertafter: '^JAVA_OPTS="-Djava.awt.headless=true'
    regexp: '^JAVA_OPTS="\${JAVA_OPTS}'
    mode: '0644'
  notify: xwiki restart
  when:
    - xwiki_appserver is match("tomcat.*")
    - tomcatjavaopts is defined
    - tomcatjavaopts

- name: apply xwiki cfg
  ansible.builtin.lineinfile:
    path: "{{ xwiki_etc }}/xwiki.cfg"
    line: "{{ item.key }}={{ item.value }}"
    regexp: '^{{ item.key }} *='
    mode: '0644'
  notify: xwiki restart
  with_dict: "{{ xwiki.cfg }}"

- name: apply xwiki properties
  ansible.builtin.lineinfile:
    path: "{{ xwiki_etc }}/xwiki.properties"
    line: "{{ item.key }}={{ item.value }}"
    regexp: '^{{ item.key }} *='
    mode: '0644'
  notify: xwiki restart
  with_dict: "{{ xwiki.properties }}"

- name: configure ReadWritePaths
  ansible.builtin.lineinfile:
    path: "{% if xwiki_appserver == 'xjetty' %}/lib/systemd/system/xwiki.service{% else %}/etc/systemd/system/{{ xwiki_appserver }}.service.d/xwiki-{{ xwiki_appserver }}-systemd.conf{% endif %}"
    line: "ReadWritePaths=/var/lib/xwiki/data {{ systemdreadwritepaths | join(' ') }}"
    regexp: '^ReadWritePaths='
  notify:
    - systemctl daemon-reload
    - xwiki restart
  when: systemdreadwritepaths

- name: copy files to tomacat conf dir
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/var/lib/tomcat10/conf/{{ item }}"
    mode: "0640"
    owner: tomcat
    group: tomcat
  notify: xwiki restart
  with_items: "{{ tomcatconffiles }}"
  when:
    - xwiki_appserver is match("tomcat.*")

# required for libreoffice
- name: create /var/lib/tomcat/.cache/ for libreoffice
  ansible.builtin.file:
    path: /var/lib/tomcat/.cache/
    state: directory
    owner: tomcat
    group: tomcat
    mode: '0755'

- name: tomcat - catalina connector
  ansible.builtin.include_tasks: tomcatcatalinaconnector.yml
  when:
    - xwiki_appserver is match("tomcat.*")

- name: ensure service is started - {{ xwiki_service }}
  ansible.builtin.systemd_service:
    state: started
    name: "{{ xwiki_service }}"

- name: setup apache2 as reverse proxy
  ansible.builtin.include_tasks: apache.yml
  when:
    - use_apache_proxy
...
